name: Deploy

on: 
  push:
    branches:
      - 'master'

jobs:
  build-test-publish:
    name: Lint, Test, Build, and Publish to NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - name: Print
        run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.VUE_STRIPE_PARTNER_ID }}
